#ifndef COMMONDEF_H
#define COMMONDEF_H

#define GAME_INDEX_CONWAYGAME 0
#define GAME_INDEX_HIGHLIFE 1
#define GAME_INDEX_PSEUDOLIFE 2
#define GAME_INDEX_2X2 3
#define GAME_INDEX_MOVE 4


#define GRID_INDEX_256 0
#define GRID_INDEX_20 1


#define GRID_SIZE_256 256
#define GRID_SIZE_20 20
#define GRID_SIZE_AUTO_FIT_LIMIT 800





#endif // COMMONDEF_H
